# Basic model provision example - essential models for any Fooocus fork
# This downloads the minimum required models to get started

[models.checkpoints.sdxl-base]
source = "huggingface"
repo = "stabilityai/stable-diffusion-xl-base-1.0"
file = "sd_xl_base_1.0.safetensors"

[models.checkpoints.sdxl-refiner]
source = "huggingface"
repo = "stabilityai/stable-diffusion-xl-refiner-1.0"
file = "sd_xl_refiner_1.0.safetensors"

[models.vae.sdxl-vae]
source = "huggingface"
repo = "stabilityai/sdxl-vae"
file = "sdxl_vae.safetensors"

[models.lora.detail-tweaker]
source = "civitai"
model_id = "58390"
# Popular LoRA for detail enhancement