# Comprehensive model provision example - includes checkpoints, LoRAs, VAEs, and ControlNets
# Suitable for users who want a full-featured setup

# Base checkpoints
[models.checkpoints.sdxl-base]
source = "huggingface"
repo = "stabilityai/stable-diffusion-xl-base-1.0"
file = "sd_xl_base_1.0.safetensors"

[models.checkpoints.sdxl-refiner]
source = "huggingface"
repo = "stabilityai/stable-diffusion-xl-refiner-1.0"
file = "sd_xl_refiner_1.0.safetensors"

[models.checkpoints.dreamshaper-xl]
source = "civitai"
version_id = "112902"
# Popular general purpose model

# VAE models
[models.vae.sdxl-vae]
source = "huggingface"
repo = "stabilityai/sdxl-vae"
file = "sdxl_vae.safetensors"

# LoRA models for style and detail enhancement
[models.lora.detail-tweaker]
source = "civitai"
version_id = "58390"

[models.lora.add-detail]
source = "civitai"
version_id = "87153"

[models.lora.film-velvia]
source = "civitai"
version_id = "125703"

# ControlNet models
[models.controlnet.canny]
source = "huggingface"
repo = "diffusers/controlnet-canny-sdxl-1.0"
file = "diffusion_pytorch_model.safetensors"

[models.controlnet.depth]
source = "huggingface"
repo = "diffusers/controlnet-depth-sdxl-1.0"
file = "diffusion_pytorch_model.safetensors"

# Upscaling models
[models.esrgan.real-esrgan]
source = "url"
url = "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth"
filename = "RealESRGAN_x4plus.pth"