name: Cleanup Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'  # Weekly on Sunday at 4 AM UTC
  workflow_run:
    workflows: ["Build Fooocus Fork Images"]
    types:
      - completed

jobs:
  cleanup-base:
    name: Cleanup base image
    uses: ./.github/workflows/delete-container-versions.yml
    with:
      package_name: 'fooocus-base'
      package_type: 'container'
      min_versions_to_keep: 3  # Keep fewer base images as they're large
    permissions:
      packages: write

  cleanup-mashb1t:
    name: Cleanup mashb1t fork images
    uses: ./.github/workflows/delete-container-versions.yml
    with:
      package_name: 'fooocus-mashb1t'
      package_type: 'container'
      min_versions_to_keep: 5
    permissions:
      packages: write

  cleanup-ruined:
    name: Cleanup ruined fork images
    uses: ./.github/workflows/delete-container-versions.yml
    with:
      package_name: 'fooocus-ruined'
      package_type: 'container'
      min_versions_to_keep: 5
    permissions:
      packages: write

  cleanup-extended:
    name: Cleanup extended fork images
    uses: ./.github/workflows/delete-container-versions.yml
    with:
      package_name: 'fooocus-extended'
      package_type: 'container'
      min_versions_to_keep: 5
    permissions:
      packages: write

  cleanup-mre:
    name: Cleanup mre fork images
    uses: ./.github/workflows/delete-container-versions.yml
    with:
      package_name: 'fooocus-mre'
      package_type: 'container'
      min_versions_to_keep: 5
    permissions:
      packages: write

  # Cleanup legacy images if they exist
  cleanup-legacy:
    name: Cleanup legacy vastai-fooocus-plus images
    uses: ./.github/workflows/delete-container-versions.yml
    continue-on-error: true  # Don't fail if package doesn't exist
    with:
      package_name: 'vastai-fooocus-plus'
      package_type: 'container'
      min_versions_to_keep: 2
    permissions:
      packages: write